[supervisord]
nodaemon=true
user=root
logfile=/dev/null
logfile_maxbytes=0
pidfile=/var/run/supervisord.pid

[program:apache]
command=/usr/local/bin/start.sh
directory=/var/www/html
autostart=true
autorestart=true
startretries=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=10

[program:gunicorn]
command=gunicorn --bind 0.0.0.0:5000 --workers 1 --timeout 120 app:app
directory=/opt/ocr
autostart=true
autorestart=true
startretries=3
environment=FLAGS_use_mkldnn="0",PADDLE_PDX_DISABLE_MODEL_SOURCE_CHECK="True"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=20
